name: Build and Test

on:
  - push
  - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: build
        run: make build

      - name: Run tests
        run: make test